# Generated by Django 4.2 on 2025-02-25 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must be a valid unicode string containing only ASCII alphanumerics, hyphens, underscores, or periods.', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
