# Generated by Django 4.2 on 2025-02-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='sub_description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
